name: Java CI with Gradle

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: set up Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Get current version
      run: |
        VERSION=$(grep 'version = "' build.gradle.kts | cut -d '"' -f2)
        echo "Current version is $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save the version for later steps

    - name: Increment patch version
      run: |
        # Split version into major, minor, patch parts
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$patch"
        echo "New version is $NEW_VERSION"

    - name: Update version in build.gradle.kts
      run: |
        sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" build.gradle.kts
        echo "Version updated to $NEW_VERSION in build.gradle.kts"

    - name: Build with Gradle
      run: ./gradlew build
