name: Java CI - Multi-stage

on:
  push:
    branches:
      - "dev"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Get current version
      run: |
        VERSION=$(grep 'version = "' build.gradle.kts | cut -d '"' -f2)
        echo "Current version is $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Increment patch version
      run: |
        IFS='.' read -r major minor patch <<< "$VERSION"
        patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$patch"
        echo "New version is $NEW_VERSION"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Update version in build.gradle.kts
      run: |
        echo "Updating version to $NEW_VERSION"
        sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" build.gradle.kts
        echo "Version updated to $NEW_VERSION in build.gradle.kts"

    - name: Commit and push the updated version
      run: |
        git config user.name "ben"
        git config user.email "benmaryuma@gmail.com"
        git add build.gradle.kts
        git commit -m "Increment patch version to $NEW_VERSION"
        git push

    - name: Build Docker image using Multistage
      run: |
        docker build -t ownedbyben/stage-app:$NEW_VERSION .
        docker tag ownedbyben/stage-app:$NEW_VERSION ownedbyben/stage-app:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ownedbyben/stage-app:$NEW_VERSION
        docker push ownedbyben/stage-app:latest


    - name: Pull and run Docker image
      run: |
        docker pull ownedbyben/stage-app:latest
        docker run --rm ownedbyben/stage-app:$NEW_VERSION
